# Generated by Django 4.2.3 on 2023-09-02 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppArtesania', '0004_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
